# Generated by Django 3.0.5 on 2021-03-13 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageQuestion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionList',
        ),
        migrations.DeleteModel(
            name='QuestionListDefault',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
