# Generated by Django 3.0.5 on 2021-03-13 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageQuestion', '0003_questionlist_questionlistdefault_questions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionListDefault',
        ),
    ]
