# Generated by Django 3.0.5 on 2021-03-13 10:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manageQuestion', '0004_delete_questionlistdefault'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionlist',
            name='active',
            field=models.CharField(default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
    ]
