# Generated by Django 3.0.5 on 2021-03-13 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageQuestion', '0005_questionlist_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionlist',
            name='active',
        ),
    ]
